name: "check-conventional-commits"
description: "Checks if all the commits (of the branch which triggered the event) comply to the conventional commits standard"
author: Alex Speranza

inputs:
  token:
    description: "Personal access token with pull permissions on repository"
    required: true

outputs:
  errors:
    description: "Number of non conventional commit messages"
    value: ${{ steps.run-script.outputs.errors }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        token: ${{ inputs.token }}
    - id: run-script
      run: |
        set -euo pipefail
        ERRORS="$(git log --grep='^\w+(\((\w|-)+\))?!?: .+$' --invert-grep -E --pretty=format:%s | awk 'END {print NR}')"
        echo "errors=$ERRORS" >> "$GITHUB_OUTPUT"
        test "$ERRORS" -eq "0"
      shell: bash
